name: jeo-plugin
recipe: wordpress
config:
  webroot: wordpress
services:
  node:
    type: node
    build:
      - npm install
  testdb:
    type: mysql
    creds:
      user: wptest
      password: wptest
      database: wptest
  appserver:
    build:
      - composer install
      - wp core download --path=wordpress
      - wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database --skip-check --path=wordpress
      - ./tests/bin/install-wp-tests.sh wptest wptest wptest test-environment testdb latest true
      - ./utils/wp-test-setup.lando.sh
    build_as_root:
      - apt-get update -y && apt-get install -y subversion
    run:
      - ./utils/wp-install.lando.sh
    overrides:
      volumes:
        - src:/app/wordpress/wp-content/plugins/jeo-plugin
        - /app/vendor
        - /app/wordpress
        - /app/test-environment
        - /app/node_modules
tooling:
  npm:
    service: node
    description: Runs npm commands
    cmd: npm
  phpunit:
    service: appserver
    description: Runs phpunit tests
    cmd: ./vendor/bin/phpunit
  build:
    description: Builds the plugin
    service: node
    cmd:
      - npm run build
  watch:
    description: Builds the plugin
    service: node
    cmd:
      - npm run start
