version: '2'

services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./docker/mariadb/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      
  wordpress:
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
    ports:
      - 80:80
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 'true'
      INFOAMAZONIAAPIKEY: ${INFOAMAZONIAAPIKEY}
      MAPBOXAPIKEY: ${MAPBOXAPIKEY}
    volumes:
      - ./src:/var/www/html/wp-content/plugins/jeo-mps
      - ./wp-content:/var/www/html/wp-content
      - ./docker/mariadb/data:/docker-entrypoint-initdb.d
      - ./docker/wordpress/.htaccess:/var/www/html/.htaccess
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=therootpassword
      - MYSQL_USER=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=wordpress
      
  watcher:
    build:
      context: .
      dockerfile: ./docker/watcher/Dockerfile
    volumes:
      - ./:/app

volumes:
  mariadb_data:
